kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        ports:
        - containerPort: 8080
          protocol: TCP
        image: registry.access.redhat.com/ubi8/ubi:latest
        command:
        - sleep
        - infinity
